# .air.toml
root = "."
tmp_dir = "tmp"

[build]
bin = "app"
cmd = "go build -o ./tmp/main ."
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp"]
exclude_file = []
log = "build-errors.log"

[color]
main = "magenta"
build = "yellow"
runner = "green"
watcher = "cyan"
app = ""

[misc]
clean_on_exit = true